const INFOUSER_UPDATE = 'INFOUSER_UPDATE'
const HOME_DATA_UPDATE = 'HOME_DATA_UPDATE'
const SEARCH_ADD =  'SEARCH_ADD'
const SEARCH_DELETE ='SEARCH_DELETE'
const SEARCH_CLEAR_ALL ='SEARCH_CLEAR_ALL'
const NUMBER_NOTIFICATION_UPDATE ='NUMBER_NOTIFICATION_UPDATE'
const NUMBER_MESSAGE_UPDATE ='NUMBER_MESSAGE_UPDATE'
export {
  INFOUSER_UPDATE,
  HOME_DATA_UPDATE,
  SEARCH_CLEAR_ALL,
  SEARCH_ADD,
  SEARCH_DELETE,
  NUMBER_NOTIFICATION_UPDATE,
  NUMBER_MESSAGE_UPDATE
};
